<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- PARENT -->
	<parent>
		<groupId>org.nlp4j</groupId>
		<artifactId>nlp4j</artifactId>
		<version>1.3.1.0</version>
	</parent>
	<artifactId>nlp4j-lucene</artifactId>
	<!-- JAR -->
	<packaging>jar</packaging>
	<name>nlp4j-lucene</name>
	<!-- https://central.sonatype.com/artifact/org.nlp4j/nlp4j-lucene/ -->
	<!-- 2026-07-30 1.0.0.0 Keyword Search -->
	<!-- 2026-08-03 1.1.0.0 Field search and aggregation -->
	<!-- 2026-08-06 1.4.0.0 Multi valued field search and aggregation -->
	<version>1.4.0.0</version>
	<description>NLP4J for Apache Lucene</description>
	<url>https://nlp4j.org/</url>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<profiles>
		<!-- profile は親pom.xml に定義されている -->
	</profiles>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.release>17</maven.compiler.release>
		<lucene.version>9.12.2</lucene.version>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<release>17</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<!-- https://mvnrepository.com/artifact/org.nlp4j/nlp4j-core -->
		<dependency>
			<groupId>org.nlp4j</groupId>
			<artifactId>nlp4j-core</artifactId>
			<version>1.3.7.21</version>
		</dependency>

		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-core</artifactId>
			<version>${lucene.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-analysis-common</artifactId>
			<version>${lucene.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-queryparser</artifactId>
			<version>${lucene.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-facet</artifactId>
			<version>${lucene.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-analysis-kuromoji</artifactId>
			<version>${lucene.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/junit/junit -->
		<!-- 3.8.2 : May 14, 2007 -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
